Bug/npj 158/ajustar retorno de processos
fabuniprojecaotag/npj-frontend pull request #6
Opened 2024-10-17 19:30 UTC by Meschick

O principal objetivo foi ajustar o bug que estavá ocorrendo ao retornar os processos vinculado ao assistido.

2024-10-28 19:28 UTC, RafaelAguiarRodrigues requested changes
Negado. Foram observadas algumas más práticas e leves erros de lógica apesar de estar funcional

2024-10-28 19:28 UTC, RafaelAguiarRodrigues commented on src/app/core/types/ListResponse.ts
Temos um tipo de retorno já existente o ListCacheEntry, então esta classe duplica um tipo já existente. Caso realmente seja necessário, deixe alguns dos atributos dela opcionais ou utilize herança para evitar duplicação e evite comentários (o código tem que ser autoexplicativo, somente em casos muito necessários se comenta).

Obs: Nomenclatura do arquivo está incorreta, estamos adotando o padrão Kebab Case.(https://www.alura.com.br/artigos/convencoes-nomenclatura-camel-pascal-kebab-snake-case?srsltid=AfmBOorbjXFypRuSlJ-xdX9zZSPbxX5yPYjo87yDYFhKoN3SCtLBlMyA)

2024-10-28 19:28 UTC, RafaelAguiarRodrigues commented on src/app/feature/assistidos/services/assistidos.service.ts
Adicionar o tipo já existente (comentado anteriormente)

2024-10-28 19:28 UTC, RafaelAguiarRodrigues commented on src/app/feature/processos/services/processos.service.ts
Método está correto porém pertence a service de assistidos (remover comentário, mesmo motivo do ListResponse)

Sugestão: Aproveitar o listarAtendimentosVinculados e só renomear para processos e a url.

2024-11-01 17:51 UTC, RafaelAguiarRodrigues reviewed
Quase pronto, só houve um pequeno engano no método da service, porém os ajustes realizados estão todos de acordo e bem implementados.

2024-11-01 17:51 UTC, RafaelAguiarRodrigues commented on src/app/feature/processos/services/processos.service.ts
Acho que não expliquei bem, mas a ideia é a seguinte:

na service de assistidos (assistidosService) temos o método pronto (listarProcessosVinculados() que recebe o cpf), podemos só atualizar ele para trazer os processos vinculado ao assistido, assim evitando a chamada da processoService e centralizando tudo na assistidoService

2024-11-03 00:09 UTC, RafaelAguiarRodrigues approved these changes
Aprovado por minha parte para Pull Request, o código está limpo, coeso e bem escrito e está funcionando

2024-11-05 19:04 UTC, jonatasmateus approved these changes
Revisão técnica feita e correção no ProcessosService aplicado.

2024-11-05 19:06 UTC, merged