remover-duplicação-de-alerta-de-erro
fabuniprojecaotag/npj-frontend pull request #7
Opened 2024-10-28 21:44 UTC by JotaPe-dev

2024-10-28 21:53 UTC, RafaelAguiarRodrigues requested changes
Recusado, alguns tratamentos de erro foram removidos juntos dos alertas e a versão do angular foi alterada, necessária a correção para o merge

2024-10-28 21:53 UTC, RafaelAguiarRodrigues commented on package.json
restaurar a versão do angular original

2024-10-28 21:53 UTC, RafaelAguiarRodrigues commented on src/app/core/components/file-list/file-list.component.ts
restaurar o this.isLoading = false para interromper o carregamento em caso de erro

2024-10-28 21:53 UTC, RafaelAguiarRodrigues commented on src/app/core/components/file-upload/file-upload.component.ts
restaurar o this.uploadProgress = 0; para resetar a barra

2024-10-28 23:06 UTC, JotaPe-dev commented on package.json
Restaurado.

2024-10-28 23:09 UTC, JotaPe-dev commented on src/app/core/components/file-list/file-list.component.ts
Restaurado apenas errei na mensagem pois coloquei (this.uploadProgress = 0) ao invés de this.isLoading = false;
mas no código esta certinho.

2024-10-28 23:09 UTC, JotaPe-dev commented on src/app/core/components/file-upload/file-upload.component.ts
Restaurado.

2024-11-05 19:13 UTC, jonatasmateus approved these changes
Correções apontadas pelo @RafaelAguiarRodrigues estão certas e foram aplicadas pelo @JotaPe-dev.

2024-11-05 19:14 UTC, merged