NPJ 164- Correção do campo instante
fabuniprojecaotag/npj-frontend pull request #9
Opened 2024-11-06 22:46 UTC by Andre-Rodriguesjr

# Correção de campo instante

Nessa A&WO foi feita a correção dos campos instante na Ficha Trabalhista e na Ficha Civil, foi colocado o campo de horas e o campo de datas.

## Verificar

Para verificar se os campos está correto basta apenas entra em atendimento, novo atendimento depois entra em Ficha Civil e Ficha Trabalhista

2024-11-23 17:39 UTC, RafaelAguiarRodrigues requested changes
Algumas mudanças precisam ser realizadas, temos usos de funções desnecessárias no código e remoção de atributos/funções importantes

2024-11-23 17:39 UTC, RafaelAguiarRodrigues commented on src/app/shared/components/form-atendimento-civil/form-atendimento-civil.component.ts
> +  get instanteData() {
Remover função instanteData() pois o toISOString() já garante que o formato retornado seja o utilizado pelo Mat-datepicker

2024-11-23 17:39 UTC, RafaelAguiarRodrigues commented on src/app/shared/components/form-atendimento-trabalhista/form-atendimento-trabalhista.component.scss
não subir estas alterações (somente são espaçamentos), não são relacionadas a tarefa

2024-11-23 17:39 UTC, RafaelAguiarRodrigues commented on src/app/shared/components/form-atendimento-trabalhista/form-atendimento-trabalhista.component.ts
> +import { map } from 'rxjs';
remover import não utilizado

2024-11-23 17:39 UTC, RafaelAguiarRodrigues commented on src/app/shared/components/form-atendimento-trabalhista/form-atendimento-trabalhista.component.ts
> +  get instanteData() {
assim como descrito anteriormente, remover o instanteData e substituir por toISOString no campo instante

2024-11-23 17:39 UTC, RafaelAguiarRodrigues commented on src/app/shared/components/form-atendimento-trabalhista/form-atendimento-trabalhista.component.ts
> +    console.log(this.formAtendimentosTrabalhista);
remover console.log()

2024-11-23 17:39 UTC, RafaelAguiarRodrigues commented on src/app/shared/components/form-atendimento-trabalhista/form-atendimento-trabalhista.component.ts
> +    window.open('http://www.seduc.go.gov.br', '_blank');
????????? 
Restaurar link para página de cadastro de assistidos

2024-11-23 17:39 UTC, RafaelAguiarRodrigues commented on src/app/shared/components/form-atendimento-civil/form-atendimento-civil.component.html
> +          <input matInput  formControlName="instante">
Restaurar o vinculo de valor entre o datepicker e o campo no ts

2024-11-23 17:39 UTC, RafaelAguiarRodrigues commented on src/app/shared/components/form-atendimento-trabalhista/form-atendimento-trabalhista.component.html
> +          <input matInput formControlName="instante" />
Assim como no atendimento civil, restaurar o vinculo entre o campo e o datepicker

2024-12-10 02:26 UTC, closed without merging

2024-12-10 02:26 UTC, jonatasmateus commented
A correção dada demorou para ser efetuada. Portanto, a tarefa será ignorada.